version: "3"

services:
  app:
    depends_on:
      - db
    build:
      context: ./node
    command: node index.js
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    depends_on:
      - app
    build:
      context: ./nginx
    ports:
      - "8080:80"
    container_name: nginx
    networks:
      - node-network
    links:
      - app

networks:
  node-network:
    driver: bridge
